stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn package
    - dpl --provider=heroku --app=clc4217-simplewebapp
