stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - mvn package
    - export PORT=5000
    - sh target/bin/simplewebapp & kill -9 $(lsof -i tcp:5000 -t)
