
stages:
  - compile
  - test
  - deploy

job 1:
  stage: compile
  script:
    - mvn compile

job 2:
  stage: test
  script:
    - mvn test

job 3:
  stage: deploy
  script:
    - mvn package
    - export PORT=5000
    - sh target/bin/simplewebapp
    - return
